name: Build
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  build:
    name: Build dependency
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install
        run: npm install
      - name: Build dependency
        run: npm run build
